### --- Rust --- ###
[[language]]
name = "rust"
formatter = { command = "rustfmt" }
auto-format = true

[language-server.rust-analyzer.config.check]
command = "clippy"

[language.debugger]
name = "lldb-dap"
transport = "stdio"
command = "lldb-dap"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
args = { program = "{0}", runInTerminal = true }


### --- C --- ###
[[language]]
name = "c"

[language.debugger]
name = "lldb-dap"
transport = "stdio"
command = "lldb-dap"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
args = { program = "{0}", runInTerminal = true }


### --- CPP --- ###
[[language]]
name = "cpp"

[language.debugger]
name = "lldb-dap"
transport = "stdio"
command = "lldb-dap"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
args = { program = "{0}", runInTerminal = true }


### --- Phython--- ###
[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff-lsp"

[language.formatter]
command = "black"
args = ["--quiet", "-"]


### --- GO lang --- ###
[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }


### --- Java --- ###
[[language]]
name = "java"
scope = "source.java"
injection-regex = "java"
file-types = ["java"]
roots = ["pom.xml", "build.gradle", ]


### --- Ruby --- ###
[[language]]
name = "ruby"
formatter = { command = "rubocop", args = ["--stdin", "foo.rb", "-a", "--stderr", "--fail-level", "fatal"] }
auto-format = true
language-servers=[{name="solargraph"}]

[language-server.solargraph]
config.diagnostics=true
config.formatting=false